sudo: required
services:
  - docker
before_install:
  - docker build -t abdelmounaimazz/docker-travis-aws-learning -f Dockerfile.dev .
script:
  - docker run -e CI=true abdelmounaimazz/docker-travis-aws-learning npm run test
