export default {
  login: "Abdelmounaim-Azz",
  id: 36277980,
  node_id: "MDQ6VXNlcjM2Mjc3OTgw",
  avatar_url: "https://avatars0.githubusercontent.com/u/36277980?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/Abdelmounaim-Azz",
  html_url: "https://github.com/Abdelmounaim-Azz",
  followers_url: "https://api.github.com/users/Abdelmounaim-Azz/followers",
  following_url:
    "https://api.github.com/users/Abdelmounaim-Azz/following{/other_user}",
  gists_url: "https://api.github.com/users/Abdelmounaim-Azz/gists{/gist_id}",
  starred_url:
    "https://api.github.com/users/Abdelmounaim-Azz/starred{/owner}{/repo}",
  subscriptions_url:
    "https://api.github.com/users/Abdelmounaim-Azz/subscriptions",
  organizations_url: "https://api.github.com/users/Abdelmounaim-Azz/orgs",
  repos_url: "https://api.github.com/users/Abdelmounaim-Azz/repos",
  events_url: "https://api.github.com/users/Abdelmounaim-Azz/events{/privacy}",
  received_events_url:
    "https://api.github.com/users/Abdelmounaim-Azz/received_events",
  type: "User",
  site_admin: false,
  name: "Sleepy_bat",
  company: null,
  blog: "",
  location: "Rabat,Agdal",
  email: "abdelmounaim.azziza@outlook.fr",
  hireable: "Looking for internship",
  bio: "Passionate about web dev  & cloud",
  twitter_username: "AbdelmounaimAzz",
  public_repos: 5,
  public_gists: 0,
  followers: 0,
  following: 8,
  created_at: "2018-02-08T19:09:44Z",
  updated_at: "2020-10-20T15:22:15Z",
};
